@startuml
skinparam packageStyle rectangle
skinparam shadowing false
hide empty members

class "1: acquisition of\nuser's login\ncredentials" as Goal #skyblue

class "1.1\nAttacker acquires\nvalid username" as User #lightgrey
class "1.2\nAttacker acquires\nvalid password" as Pass #lightgrey

class "1.1.1\nLogin page error\nused to determine\nvalidity" as UserError #lightgrey
class "1.1.2\nAttacker gets user\nto disclose it" as UserDisclose #lightgrey
class "1.1.3\nReseting password error\nused to determine\nvalidity" as ResetingError #lightgrey

class "1.2.1\nAttacker finds\npassword by a\nbrute-force attack" as Brute #lightgrey
class "1.2.2\nAttacker gets user\nto disclose\npassword" as PassDisclose #lightgrey
class "1.2.3\nAttacker has database access" as DBAccess #lightgrey
class "1.2.4\nAttacker uses SQL injection" as SQLInjection #lightgrey

Goal -- User : "  AND"
Goal -- Pass : "  AND"

User -- UserError : "  OR"
User -- UserDisclose : "  OR"
User -- ResetingError : "  OR"

Pass -- Brute : "  OR"
Pass -- PassDisclose : "  OR"
Pass -- DBAccess : "  OR"
Pass -- SQLInjection : "  OR"

@endum